"""Independently launchable Forge Studio application surface."""

from .application import StudioApplication
from .backend import BackendAdapter
from .composition import (
    BACKEND_KINDS,
    EXTENSION,
    HEADLESS_BACKEND,
    HOST_NAMES,
    MOCK_BACKEND,
    STANDALONE,
    ExtensionHost,
    InlineExecutor,
    StandaloneHost,
    StudioComposition,
    StudioExecutor,
    StudioHost,
    StudioReadiness,
    StudioRuntimeServices,
    build_extension,
    build_standalone,
)
from .contracts import (
    AttentionBackend,
    BackendStatus,
    CancellationResult,
    DeviceType,
    DtypePolicy,
    GeneratedResult,
    GenerationJobIdentity,
    GenerationRequest,
    JobState,
    ModelCapability,
    ModelResidency,
    ModelSummary,
    ProgressEvent,
    StructuredError,
    StudioError,
)
from .mock_backend import MockBackend
from .result_delivery import (
    CasePolicy,
    ResultAsset,
    ResultPayload,
    ResultRegistry,
    detect_case_policy,
)

__all__ = (
    "AttentionBackend",
    "BACKEND_KINDS",
    "BackendAdapter",
    "BackendStatus",
    "CancellationResult",
    "CasePolicy",
    "DeviceType",
    "DtypePolicy",
    "EXTENSION",
    "ExtensionHost",
    "HEADLESS_BACKEND",
    "GeneratedResult",
    "GenerationJobIdentity",
    "GenerationRequest",
    "HOST_NAMES",
    "InlineExecutor",
    "JobState",
    "MOCK_BACKEND",
    "MockBackend",
    "ModelCapability",
    "ModelResidency",
    "ModelSummary",
    "ProgressEvent",
    "ResultAsset",
    "ResultPayload",
    "ResultRegistry",
    "STANDALONE",
    "StandaloneHost",
    "StructuredError",
    "StudioApplication",
    "StudioComposition",
    "StudioError",
    "StudioExecutor",
    "StudioHost",
    "StudioReadiness",
    "StudioRuntimeServices",
    "build_extension",
    "build_standalone",
    "detect_case_policy",
)

__version__ = "0.1.0-alpha-s0"
